/**
 * Build the typed icon registry from the cleaned SVGs.
 *
 * Usage: bun run scripts/build-icon-registry.ts
 *
 * Walks src/assets/icons/<category>/<slug>.svg and emits
 * src/components/ui/icon/registry.gen.ts — the `IconName` union (every icon as
 * `category/slug`) plus `ICON_NAMES`. The <Icon> component loads a name through
 * an `import.meta.glob` map, so this only keeps the union in sync with the files
 * on disk. Rerun after adding or renaming icons.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ICONS = join(import.meta.dir, '../src/assets/icons')
const REGISTRY_OUT = join(
  import.meta.dir,
  '../src/components/ui/icon/registry.gen.ts'
)

const names: string[] = []
for (const category of readdirSync(ICONS).sort()) {
  const dir = join(ICONS, category)
  if (!statSync(dir).isDirectory()) continue
  for (const file of readdirSync(dir).sort()) {
    if (file.endsWith('.svg'))
      names.push(`${category}/${file.replace(/\.svg$/, '')}`)
  }
}

const registry = `// Generated by scripts/build-icon-registry.ts — do not edit by hand.

/** Every icon in the cleaned set, as \`category/slug\`. */
export type IconName =
${names.map((n) => `  | '${n}'`).join('\n')}

export const ICON_NAMES: readonly IconName[] = [
${names.map((n) => `  '${n}',`).join('\n')}
]
`
writeFileSync(REGISTRY_OUT, registry)
console.log(
  `registry: ${names.length} icons → src/components/ui/icon/registry.gen.ts`
)
