// Generated by scripts/build-icon-registry.ts — do not edit by hand.

/** Every icon in the cleaned set, as `category/slug`. */
export type IconName =
  | 'aeldari/aeldari'
  | 'aeldari/alaitoc'
  | 'aeldari/altansar'
  | 'aeldari/asuryani'
  | 'aeldari/avatar-of-khaine'
  | 'aeldari/biel-tan'
  | 'aeldari/cult-of-strife'
  | 'aeldari/dire-avengers'
  | 'aeldari/drukhari-1'
  | 'aeldari/drukhari-2'
  | 'aeldari/drukhari-3'
  | 'aeldari/drukhari-4'
  | 'aeldari/exodites'
  | 'aeldari/fire-dragons'
  | 'aeldari/guardians'
  | 'aeldari/harlequin-masque-of-the-veiled-path'
  | 'aeldari/harlequins'
  | 'aeldari/howling-banshees'
  | 'aeldari/iyanden'
  | 'aeldari/kabal-of-the-black-heart'
  | 'aeldari/kabal-of-the-flayed-skull'
  | 'aeldari/morai-heg'
  | 'aeldari/mymeara'
  | 'aeldari/outcasts'
  | 'aeldari/prophets-of-flesh'
  | 'aeldari/saim-hann'
  | 'aeldari/ulthwe'
  | 'aeldari/warp-spiders'
  | 'aeldari/webway'
  | 'aeldari/ynnari'
  | 'aeldari/ynnead'
  | 'chaos/alpha-legion'
  | 'chaos/black-legion'
  | 'chaos/chaos-daemons-2'
  | 'chaos/chaos-daemons'
  | 'chaos/chaos-star-01'
  | 'chaos/dark-mechanicum'
  | 'chaos/death-guard'
  | 'chaos/emperor-s-children'
  | 'chaos/extinction-angels'
  | 'chaos/eye-of-horus'
  | 'chaos/heretic-astartes'
  | 'chaos/iron-warriors'
  | 'chaos/khorne'
  | 'chaos/legio-mortis'
  | 'chaos/lost-and-damned'
  | 'chaos/luna-wolves'
  | 'chaos/malice'
  | 'chaos/night-lords'
  | 'chaos/nurgle'
  | 'chaos/pre-heresy-eye-of-horus'
  | 'chaos/pre-heresy-iron-warriors'
  | 'chaos/questor-traitoris'
  | 'chaos/red-corsairs'
  | 'chaos/renegades-and-heretics'
  | 'chaos/slaanesh-icon-01'
  | 'chaos/slaanesh'
  | 'chaos/sons-of-horus'
  | 'chaos/sons-of-malice'
  | 'chaos/the-fallen'
  | 'chaos/thousand-sons-pre-heresy'
  | 'chaos/thousand-sons'
  | 'chaos/titanicus-traitoris'
  | 'chaos/tyrant-s-legion'
  | 'chaos/tzeentch'
  | 'chaos/word-bearers'
  | 'chaos/world-eaters'
  | 'chaos/zuvassin'
  | 'druhkari/cult-of-strife'
  | 'druhkari/dark-eldar'
  | 'druhkari/drukhari-1'
  | 'druhkari/drukhari-2'
  | 'druhkari/drukhari-3'
  | 'druhkari/drukhari-4'
  | 'druhkari/kabal-of-the-black-heart'
  | 'druhkari/kabal-of-the-flayed-skull'
  | 'druhkari/prophets-of-flesh'
  | 'general/armour-penetration'
  | 'general/assault-01'
  | 'general/assault'
  | 'general/attacks'
  | 'general/ballistic-skill'
  | 'general/damage'
  | 'general/dedicated-transport'
  | 'general/devestator-01'
  | 'general/elites-b'
  | 'general/elites'
  | 'general/fast-attack'
  | 'general/flyer'
  | 'general/fortification'
  | 'general/grenade'
  | 'general/heavy-support-b'
  | 'general/heavy-support'
  | 'general/heavy'
  | 'general/hq'
  | 'general/kill-team'
  | 'general/leadership'
  | 'general/lord-of-war'
  | 'general/melee'
  | 'general/move'
  | 'general/pistol'
  | 'general/range'
  | 'general/rapid-fire'
  | 'general/rogue-trader'
  | 'general/save'
  | 'general/skull-laurals'
  | 'general/strength'
  | 'general/sword-01'
  | 'general/sword-02'
  | 'general/sword-03'
  | 'general/sword-04'
  | 'general/tactical-01'
  | 'general/tactical-02'
  | 'general/toughness'
  | 'general/troops'
  | 'general/type'
  | 'general/user'
  | 'general/weapon-skill'
  | 'general/wounds'
  | 'general/xenos'
  | 'genestealer-cult/bladed-cog'
  | 'genestealer-cult/four-armed-emperor'
  | 'genestealer-cult/genestealer-cults'
  | 'genestealer-cult/hivecult'
  | 'genestealer-cult/pauper-princes'
  | 'genestealer-cult/rusted-claw'
  | 'genestealer-cult/twisted-helix'
  | 'imperium/133rd-lambdan-lions'
  | 'imperium/32nd-thetoid-eagles'
  | 'imperium/43rd-iotan-dragons'
  | 'imperium/54th-psian-jakals'
  | 'imperium/absolvers'
  | 'imperium/accipiters'
  | 'imperium/adepta-sororitas'
  | 'imperium/adeptus-administratum'
  | 'imperium/adeptus-arbites-2'
  | 'imperium/adeptus-arbites'
  | 'imperium/adeptus-astartes'
  | 'imperium/adeptus-astra-telepathica'
  | 'imperium/adeptus-astronomica'
  | 'imperium/adeptus-custodes'
  | 'imperium/adeptus-mechanicus'
  | 'imperium/adeptus-ministorum'
  | 'imperium/adeptus-terra'
  | 'imperium/aeronautica-imperialis'
  | 'imperium/agripinaa'
  | 'imperium/alpha-legion'
  | 'imperium/angels-eradicant'
  | 'imperium/angels-of-absolution'
  | 'imperium/angels-of-defiance'
  | 'imperium/angels-of-iron'
  | 'imperium/angels-of-redemption'
  | 'imperium/angels-of-vengeance'
  | 'imperium/angels-of-vigilance'
  | 'imperium/angels-penitent'
  | 'imperium/apothecarium-01'
  | 'imperium/apothecarium-02'
  | 'imperium/ashen-claws'
  | 'imperium/assassinorum'
  | 'imperium/astra-militarum'
  | 'imperium/astral-claws'
  | 'imperium/auxilia-myrmidon'
  | 'imperium/avengers'
  | 'imperium/avenging-sons'
  | 'imperium/black-dragons'
  | 'imperium/black-templars'
  | 'imperium/black-wings'
  | 'imperium/blades-of-vengeance'
  | 'imperium/blood-angels'
  | 'imperium/blood-drinkers'
  | 'imperium/blood-ravens'
  | 'imperium/blood-swords'
  | 'imperium/bloodied-hunter'
  | 'imperium/bloodmaws'
  | 'imperium/bolter-mkv-02'
  | 'imperium/bolter-mkv'
  | 'imperium/cadian-gate'
  | 'imperium/callidus-temple'
  | 'imperium/carcharodons'
  | 'imperium/celestial-lions'
  | 'imperium/centurio-ordinatus'
  | 'imperium/centurion-honour'
  | 'imperium/chaplain'
  | 'imperium/charnel-guard'
  | 'imperium/collegia-titanica'
  | 'imperium/consecrators'
  | 'imperium/crimson-talons'
  | 'imperium/crux-terminatus-01'
  | 'imperium/culexus-temple'
  | 'imperium/cult-mechanicus'
  | 'imperium/dark-angels'
  | 'imperium/dark-brotherhood'
  | 'imperium/death-company'
  | 'imperium/death-eagles'
  | 'imperium/death-spectres'
  | 'imperium/deathwatch'
  | 'imperium/deathwing'
  | 'imperium/deathwolves'
  | 'imperium/destroyers'
  | 'imperium/disciples-of-caliban'
  | 'imperium/dragonspears-2'
  | 'imperium/dragonspears'
  | 'imperium/drakeslayers'
  | 'imperium/emperor-s-spears'
  | 'imperium/eversor-temple'
  | 'imperium/executioners'
  | 'imperium/exorcists'
  | 'imperium/fire-hawks'
  | 'imperium/flesh-tearers'
  | 'imperium/graia'
  | 'imperium/grey-knights'
  | 'imperium/grimbloods'
  | 'imperium/guardians-of-the-covenant'
  | 'imperium/high-lords-of-terra'
  | 'imperium/imperial-fists'
  | 'imperium/imperial-knights'
  | 'imperium/imperial-lasgun'
  | 'imperium/imperial-lasguns-crossed'
  | 'imperium/imperial-navy-2'
  | 'imperium/imperial-navy'
  | 'imperium/imperium-of-man-01'
  | 'imperium/imperium-of-man-02'
  | 'imperium/inquisition-1'
  | 'imperium/inquisition-2'
  | 'imperium/invictors'
  | 'imperium/iron-hands'
  | 'imperium/iron-knights-2'
  | 'imperium/iron-knights'
  | 'imperium/iron-lords'
  | 'imperium/ironwolves'
  | 'imperium/kill-team'
  | 'imperium/knights-of-blood'
  | 'imperium/lamenters'
  | 'imperium/legio-cybernetica'
  | 'imperium/legio-gryphonicus'
  | 'imperium/legion-of-the-damned'
  | 'imperium/librarian-codicier'
  | 'imperium/librarian-epistolary'
  | 'imperium/librarian-lexicanum'
  | 'imperium/librarius-01'
  | 'imperium/librarius-02'
  | 'imperium/logan-grimnar'
  | 'imperium/lucius'
  | 'imperium/mars'
  | 'imperium/metalica'
  | 'imperium/militarum-tempestus-ordo-tempestus'
  | 'imperium/minotaurs'
  | 'imperium/navis-nobilite'
  | 'imperium/necropolis-hawks'
  | 'imperium/novamarines'
  | 'imperium/officio-assassinorum'
  | 'imperium/order-of-our-martyred-lady'
  | 'imperium/order-of-the-argent-shroud'
  | 'imperium/order-of-the-bloody-rose'
  | 'imperium/order-of-the-ebon-chalice'
  | 'imperium/order-of-the-valorous-heart'
  | 'imperium/ordo-malleus'
  | 'imperium/ordo-reductor'
  | 'imperium/palatine-aquila'
  | 'imperium/planetary-governor'
  | 'imperium/pre-heresy-dark-angels'
  | 'imperium/pre-heresy-eye-of-horus'
  | 'imperium/pre-heresy-iron-warriors'
  | 'imperium/questor-imperialis'
  | 'imperium/questor-mechanicus'
  | 'imperium/raptor-imperialis'
  | 'imperium/raptors'
  | 'imperium/raven-guard'
  | 'imperium/ravenwing'
  | 'imperium/reclusiam'
  | 'imperium/red-moons'
  | 'imperium/red-scorpions'
  | 'imperium/retributors'
  | 'imperium/rogue-traders'
  | 'imperium/ryza'
  | 'imperium/salamanders'
  | 'imperium/silver-skulls'
  | 'imperium/silver-templars'
  | 'imperium/sisters-of-battle'
  | 'imperium/sisters-of-silence'
  | 'imperium/skitarii'
  | 'imperium/skull-laurals'
  | 'imperium/solar-auxilia'
  | 'imperium/sons-of-medusa-2'
  | 'imperium/sons-of-medusa'
  | 'imperium/sons-of-morkai'
  | 'imperium/sons-of-the-phoenix'
  | 'imperium/soul-drinkers'
  | 'imperium/space-wolves'
  | 'imperium/star-dragons'
  | 'imperium/star-phantoms'
  | 'imperium/steel-confessors'
  | 'imperium/steel-legion'
  | 'imperium/stormwolves'
  | 'imperium/stygies-viii'
  | 'imperium/talons-of-the-emperor'
  | 'imperium/tanith'
  | 'imperium/temple-cullexus'
  | 'imperium/temple-eversor'
  | 'imperium/the-sea-wolf'
  | 'imperium/the-wolf-that-stalks-between-the-stars'
  | 'imperium/third-covenent'
  | 'imperium/thousand-sons-pre-heresy'
  | 'imperium/tome-keepers'
  | 'imperium/ultramarines'
  | 'imperium/vindicare-temple'
  | 'imperium/void-tridents'
  | 'imperium/white-scars'
  | 'necrons/c-tan'
  | 'necrons/mephrit-dark'
  | 'necrons/mephrit-lord-glyphs-1'
  | 'necrons/mephrit-lord-glyphs-2'
  | 'necrons/mephrit-lord-glyphs-3'
  | 'necrons/mephrit-lord-glyphs-4'
  | 'necrons/mephrit-overlord-glyphs-1'
  | 'necrons/mephrit-overlord-glyphs-2'
  | 'necrons/mephrit-overlord-glyphs-3'
  | 'necrons/mephrit-overlord-glyphs-4'
  | 'necrons/mephrit-phalanx-glyphs-1'
  | 'necrons/mephrit-phalanx-glyphs-2'
  | 'necrons/mephrit-phalanx-glyphs-3'
  | 'necrons/mephrit-phalanx-glyphs-4'
  | 'necrons/mephrit'
  | 'necrons/necrons-dark'
  | 'necrons/necrons'
  | 'necrons/nephrekh-dark'
  | 'necrons/nephrekh-lord-glyphs-1'
  | 'necrons/nephrekh-lord-glyphs-2'
  | 'necrons/nephrekh-lord-glyphs-3'
  | 'necrons/nephrekh-lord-glyphs-4'
  | 'necrons/nephrekh-overlord-glyphs-1'
  | 'necrons/nephrekh-overlord-glyphs-2'
  | 'necrons/nephrekh-overlord-glyphs-3'
  | 'necrons/nephrekh-overlord-glyphs-4'
  | 'necrons/nephrekh-phalanx-glyphs-1'
  | 'necrons/nephrekh-phalanx-glyphs-2'
  | 'necrons/nephrekh-phalanx-glyphs-3'
  | 'necrons/nephrekh-phalanx-glyphs-4'
  | 'necrons/nephrekh'
  | 'necrons/nihilakh-dark'
  | 'necrons/nihilakh-lord-glyphs-1'
  | 'necrons/nihilakh-lord-glyphs-2'
  | 'necrons/nihilakh-lord-glyphs-3'
  | 'necrons/nihilakh-lord-glyphs-4'
  | 'necrons/nihilakh-overlord-glyphs-1'
  | 'necrons/nihilakh-overlord-glyphs-2'
  | 'necrons/nihilakh-overlord-glyphs-3'
  | 'necrons/nihilakh-overlord-glyphs-4'
  | 'necrons/nihilakh-phalanx-glyphs-1'
  | 'necrons/nihilakh-phalanx-glyphs-2'
  | 'necrons/nihilakh-phalanx-glyphs-3'
  | 'necrons/nihilakh-phalanx-glyphs-4'
  | 'necrons/nihilakh'
  | 'necrons/novokh-dark'
  | 'necrons/novokh-lord-glyphs-1'
  | 'necrons/novokh-lord-glyphs-2'
  | 'necrons/novokh-lord-glyphs-3'
  | 'necrons/novokh-lord-glyphs-4'
  | 'necrons/novokh-overlord-glyphs-1'
  | 'necrons/novokh-overlord-glyphs-2'
  | 'necrons/novokh-overlord-glyphs-3'
  | 'necrons/novokh-overlord-glyphs-4'
  | 'necrons/novokh-phalanx-glyphs-1'
  | 'necrons/novokh-phalanx-glyphs-2'
  | 'necrons/novokh-phalanx-glyphs-3'
  | 'necrons/novokh-phalanx-glyphs-4'
  | 'necrons/novokh'
  | 'necrons/sautekh-dark'
  | 'necrons/sautekh-lord-glyphs-1'
  | 'necrons/sautekh-lord-glyphs-2'
  | 'necrons/sautekh-lord-glyphs-3'
  | 'necrons/sautekh-lord-glyphs-4'
  | 'necrons/sautekh-overlord-glyphs-1'
  | 'necrons/sautekh-overlord-glyphs-2'
  | 'necrons/sautekh-overlord-glyphs-3'
  | 'necrons/sautekh-overlord-glyphs-4'
  | 'necrons/sautekh'
  | 'necrons/szarekhan-dark'
  | 'necrons/szarekhan'
  | 'orks/bad-moons-2'
  | 'orks/bad-moons'
  | 'orks/blood-axes-copy'
  | 'orks/deathskulls'
  | 'orks/evil-sunz'
  | 'orks/goffs'
  | 'orks/gorkamorka'
  | 'orks/gretchin'
  | 'orks/orks'
  | 'orks/snakebites'
  | 'orks/snotlings'
  | 'orks/squigs'
  | 'tau/air-caste'
  | 'tau/au-taal'
  | 'tau/bork-an'
  | 'tau/d-yanoi'
  | 'tau/dalyth'
  | 'tau/earth-caste'
  | 'tau/elsy-eir'
  | 'tau/ethereal-caste'
  | 'tau/fal-shia'
  | 'tau/farsight-enclaves'
  | 'tau/fe-saan'
  | 'tau/fi-rios'
  | 'tau/fire-caste'
  | 'tau/ke-lshan'
  | 'tau/kor-tal'
  | 'tau/kroot'
  | 'tau/ksi-m-yen'
  | 'tau/mu-gulath'
  | 'tau/n-dras'
  | 'tau/sa-cea'
  | 'tau/t-au-n'
  | 'tau/t-au-number-0'
  | 'tau/t-au-number-1'
  | 'tau/t-au-number-2'
  | 'tau/t-au-number-3'
  | 'tau/t-au-number-4'
  | 'tau/t-au-number-5'
  | 'tau/t-au-number-6'
  | 'tau/t-au-number-7'
  | 'tau/t-au'
  | 'tau/t-olku'
  | 'tau/tash-var'
  | 'tau/tashvar'
  | 'tau/tau-num0'
  | 'tau/tau-num1'
  | 'tau/tau-num2'
  | 'tau/tau-num3'
  | 'tau/tau-num4'
  | 'tau/tau-num5'
  | 'tau/tau-num6'
  | 'tau/tau-num7'
  | 'tau/tau'
  | 'tau/vash-ya'
  | 'tau/vior-la'
  | 'tau/water-caste'
  | 'tau/yo-vai'
  | 'tyranid/tyranids'
  | 'xenos/blackstone-fortress'
  | 'xenos/hrud'
  | 'xenos/jokaero'
  | 'xenos/xenos'

export const ICON_NAMES: readonly IconName[] = [
  'aeldari/aeldari',
  'aeldari/alaitoc',
  'aeldari/altansar',
  'aeldari/asuryani',
  'aeldari/avatar-of-khaine',
  'aeldari/biel-tan',
  'aeldari/cult-of-strife',
  'aeldari/dire-avengers',
  'aeldari/drukhari-1',
  'aeldari/drukhari-2',
  'aeldari/drukhari-3',
  'aeldari/drukhari-4',
  'aeldari/exodites',
  'aeldari/fire-dragons',
  'aeldari/guardians',
  'aeldari/harlequin-masque-of-the-veiled-path',
  'aeldari/harlequins',
  'aeldari/howling-banshees',
  'aeldari/iyanden',
  'aeldari/kabal-of-the-black-heart',
  'aeldari/kabal-of-the-flayed-skull',
  'aeldari/morai-heg',
  'aeldari/mymeara',
  'aeldari/outcasts',
  'aeldari/prophets-of-flesh',
  'aeldari/saim-hann',
  'aeldari/ulthwe',
  'aeldari/warp-spiders',
  'aeldari/webway',
  'aeldari/ynnari',
  'aeldari/ynnead',
  'chaos/alpha-legion',
  'chaos/black-legion',
  'chaos/chaos-daemons-2',
  'chaos/chaos-daemons',
  'chaos/chaos-star-01',
  'chaos/dark-mechanicum',
  'chaos/death-guard',
  'chaos/emperor-s-children',
  'chaos/extinction-angels',
  'chaos/eye-of-horus',
  'chaos/heretic-astartes',
  'chaos/iron-warriors',
  'chaos/khorne',
  'chaos/legio-mortis',
  'chaos/lost-and-damned',
  'chaos/luna-wolves',
  'chaos/malice',
  'chaos/night-lords',
  'chaos/nurgle',
  'chaos/pre-heresy-eye-of-horus',
  'chaos/pre-heresy-iron-warriors',
  'chaos/questor-traitoris',
  'chaos/red-corsairs',
  'chaos/renegades-and-heretics',
  'chaos/slaanesh-icon-01',
  'chaos/slaanesh',
  'chaos/sons-of-horus',
  'chaos/sons-of-malice',
  'chaos/the-fallen',
  'chaos/thousand-sons-pre-heresy',
  'chaos/thousand-sons',
  'chaos/titanicus-traitoris',
  'chaos/tyrant-s-legion',
  'chaos/tzeentch',
  'chaos/word-bearers',
  'chaos/world-eaters',
  'chaos/zuvassin',
  'druhkari/cult-of-strife',
  'druhkari/dark-eldar',
  'druhkari/drukhari-1',
  'druhkari/drukhari-2',
  'druhkari/drukhari-3',
  'druhkari/drukhari-4',
  'druhkari/kabal-of-the-black-heart',
  'druhkari/kabal-of-the-flayed-skull',
  'druhkari/prophets-of-flesh',
  'general/armour-penetration',
  'general/assault-01',
  'general/assault',
  'general/attacks',
  'general/ballistic-skill',
  'general/damage',
  'general/dedicated-transport',
  'general/devestator-01',
  'general/elites-b',
  'general/elites',
  'general/fast-attack',
  'general/flyer',
  'general/fortification',
  'general/grenade',
  'general/heavy-support-b',
  'general/heavy-support',
  'general/heavy',
  'general/hq',
  'general/kill-team',
  'general/leadership',
  'general/lord-of-war',
  'general/melee',
  'general/move',
  'general/pistol',
  'general/range',
  'general/rapid-fire',
  'general/rogue-trader',
  'general/save',
  'general/skull-laurals',
  'general/strength',
  'general/sword-01',
  'general/sword-02',
  'general/sword-03',
  'general/sword-04',
  'general/tactical-01',
  'general/tactical-02',
  'general/toughness',
  'general/troops',
  'general/type',
  'general/user',
  'general/weapon-skill',
  'general/wounds',
  'general/xenos',
  'genestealer-cult/bladed-cog',
  'genestealer-cult/four-armed-emperor',
  'genestealer-cult/genestealer-cults',
  'genestealer-cult/hivecult',
  'genestealer-cult/pauper-princes',
  'genestealer-cult/rusted-claw',
  'genestealer-cult/twisted-helix',
  'imperium/133rd-lambdan-lions',
  'imperium/32nd-thetoid-eagles',
  'imperium/43rd-iotan-dragons',
  'imperium/54th-psian-jakals',
  'imperium/absolvers',
  'imperium/accipiters',
  'imperium/adepta-sororitas',
  'imperium/adeptus-administratum',
  'imperium/adeptus-arbites-2',
  'imperium/adeptus-arbites',
  'imperium/adeptus-astartes',
  'imperium/adeptus-astra-telepathica',
  'imperium/adeptus-astronomica',
  'imperium/adeptus-custodes',
  'imperium/adeptus-mechanicus',
  'imperium/adeptus-ministorum',
  'imperium/adeptus-terra',
  'imperium/aeronautica-imperialis',
  'imperium/agripinaa',
  'imperium/alpha-legion',
  'imperium/angels-eradicant',
  'imperium/angels-of-absolution',
  'imperium/angels-of-defiance',
  'imperium/angels-of-iron',
  'imperium/angels-of-redemption',
  'imperium/angels-of-vengeance',
  'imperium/angels-of-vigilance',
  'imperium/angels-penitent',
  'imperium/apothecarium-01',
  'imperium/apothecarium-02',
  'imperium/ashen-claws',
  'imperium/assassinorum',
  'imperium/astra-militarum',
  'imperium/astral-claws',
  'imperium/auxilia-myrmidon',
  'imperium/avengers',
  'imperium/avenging-sons',
  'imperium/black-dragons',
  'imperium/black-templars',
  'imperium/black-wings',
  'imperium/blades-of-vengeance',
  'imperium/blood-angels',
  'imperium/blood-drinkers',
  'imperium/blood-ravens',
  'imperium/blood-swords',
  'imperium/bloodied-hunter',
  'imperium/bloodmaws',
  'imperium/bolter-mkv-02',
  'imperium/bolter-mkv',
  'imperium/cadian-gate',
  'imperium/callidus-temple',
  'imperium/carcharodons',
  'imperium/celestial-lions',
  'imperium/centurio-ordinatus',
  'imperium/centurion-honour',
  'imperium/chaplain',
  'imperium/charnel-guard',
  'imperium/collegia-titanica',
  'imperium/consecrators',
  'imperium/crimson-talons',
  'imperium/crux-terminatus-01',
  'imperium/culexus-temple',
  'imperium/cult-mechanicus',
  'imperium/dark-angels',
  'imperium/dark-brotherhood',
  'imperium/death-company',
  'imperium/death-eagles',
  'imperium/death-spectres',
  'imperium/deathwatch',
  'imperium/deathwing',
  'imperium/deathwolves',
  'imperium/destroyers',
  'imperium/disciples-of-caliban',
  'imperium/dragonspears-2',
  'imperium/dragonspears',
  'imperium/drakeslayers',
  'imperium/emperor-s-spears',
  'imperium/eversor-temple',
  'imperium/executioners',
  'imperium/exorcists',
  'imperium/fire-hawks',
  'imperium/flesh-tearers',
  'imperium/graia',
  'imperium/grey-knights',
  'imperium/grimbloods',
  'imperium/guardians-of-the-covenant',
  'imperium/high-lords-of-terra',
  'imperium/imperial-fists',
  'imperium/imperial-knights',
  'imperium/imperial-lasgun',
  'imperium/imperial-lasguns-crossed',
  'imperium/imperial-navy-2',
  'imperium/imperial-navy',
  'imperium/imperium-of-man-01',
  'imperium/imperium-of-man-02',
  'imperium/inquisition-1',
  'imperium/inquisition-2',
  'imperium/invictors',
  'imperium/iron-hands',
  'imperium/iron-knights-2',
  'imperium/iron-knights',
  'imperium/iron-lords',
  'imperium/ironwolves',
  'imperium/kill-team',
  'imperium/knights-of-blood',
  'imperium/lamenters',
  'imperium/legio-cybernetica',
  'imperium/legio-gryphonicus',
  'imperium/legion-of-the-damned',
  'imperium/librarian-codicier',
  'imperium/librarian-epistolary',
  'imperium/librarian-lexicanum',
  'imperium/librarius-01',
  'imperium/librarius-02',
  'imperium/logan-grimnar',
  'imperium/lucius',
  'imperium/mars',
  'imperium/metalica',
  'imperium/militarum-tempestus-ordo-tempestus',
  'imperium/minotaurs',
  'imperium/navis-nobilite',
  'imperium/necropolis-hawks',
  'imperium/novamarines',
  'imperium/officio-assassinorum',
  'imperium/order-of-our-martyred-lady',
  'imperium/order-of-the-argent-shroud',
  'imperium/order-of-the-bloody-rose',
  'imperium/order-of-the-ebon-chalice',
  'imperium/order-of-the-valorous-heart',
  'imperium/ordo-malleus',
  'imperium/ordo-reductor',
  'imperium/palatine-aquila',
  'imperium/planetary-governor',
  'imperium/pre-heresy-dark-angels',
  'imperium/pre-heresy-eye-of-horus',
  'imperium/pre-heresy-iron-warriors',
  'imperium/questor-imperialis',
  'imperium/questor-mechanicus',
  'imperium/raptor-imperialis',
  'imperium/raptors',
  'imperium/raven-guard',
  'imperium/ravenwing',
  'imperium/reclusiam',
  'imperium/red-moons',
  'imperium/red-scorpions',
  'imperium/retributors',
  'imperium/rogue-traders',
  'imperium/ryza',
  'imperium/salamanders',
  'imperium/silver-skulls',
  'imperium/silver-templars',
  'imperium/sisters-of-battle',
  'imperium/sisters-of-silence',
  'imperium/skitarii',
  'imperium/skull-laurals',
  'imperium/solar-auxilia',
  'imperium/sons-of-medusa-2',
  'imperium/sons-of-medusa',
  'imperium/sons-of-morkai',
  'imperium/sons-of-the-phoenix',
  'imperium/soul-drinkers',
  'imperium/space-wolves',
  'imperium/star-dragons',
  'imperium/star-phantoms',
  'imperium/steel-confessors',
  'imperium/steel-legion',
  'imperium/stormwolves',
  'imperium/stygies-viii',
  'imperium/talons-of-the-emperor',
  'imperium/tanith',
  'imperium/temple-cullexus',
  'imperium/temple-eversor',
  'imperium/the-sea-wolf',
  'imperium/the-wolf-that-stalks-between-the-stars',
  'imperium/third-covenent',
  'imperium/thousand-sons-pre-heresy',
  'imperium/tome-keepers',
  'imperium/ultramarines',
  'imperium/vindicare-temple',
  'imperium/void-tridents',
  'imperium/white-scars',
  'necrons/c-tan',
  'necrons/mephrit-dark',
  'necrons/mephrit-lord-glyphs-1',
  'necrons/mephrit-lord-glyphs-2',
  'necrons/mephrit-lord-glyphs-3',
  'necrons/mephrit-lord-glyphs-4',
  'necrons/mephrit-overlord-glyphs-1',
  'necrons/mephrit-overlord-glyphs-2',
  'necrons/mephrit-overlord-glyphs-3',
  'necrons/mephrit-overlord-glyphs-4',
  'necrons/mephrit-phalanx-glyphs-1',
  'necrons/mephrit-phalanx-glyphs-2',
  'necrons/mephrit-phalanx-glyphs-3',
  'necrons/mephrit-phalanx-glyphs-4',
  'necrons/mephrit',
  'necrons/necrons-dark',
  'necrons/necrons',
  'necrons/nephrekh-dark',
  'necrons/nephrekh-lord-glyphs-1',
  'necrons/nephrekh-lord-glyphs-2',
  'necrons/nephrekh-lord-glyphs-3',
  'necrons/nephrekh-lord-glyphs-4',
  'necrons/nephrekh-overlord-glyphs-1',
  'necrons/nephrekh-overlord-glyphs-2',
  'necrons/nephrekh-overlord-glyphs-3',
  'necrons/nephrekh-overlord-glyphs-4',
  'necrons/nephrekh-phalanx-glyphs-1',
  'necrons/nephrekh-phalanx-glyphs-2',
  'necrons/nephrekh-phalanx-glyphs-3',
  'necrons/nephrekh-phalanx-glyphs-4',
  'necrons/nephrekh',
  'necrons/nihilakh-dark',
  'necrons/nihilakh-lord-glyphs-1',
  'necrons/nihilakh-lord-glyphs-2',
  'necrons/nihilakh-lord-glyphs-3',
  'necrons/nihilakh-lord-glyphs-4',
  'necrons/nihilakh-overlord-glyphs-1',
  'necrons/nihilakh-overlord-glyphs-2',
  'necrons/nihilakh-overlord-glyphs-3',
  'necrons/nihilakh-overlord-glyphs-4',
  'necrons/nihilakh-phalanx-glyphs-1',
  'necrons/nihilakh-phalanx-glyphs-2',
  'necrons/nihilakh-phalanx-glyphs-3',
  'necrons/nihilakh-phalanx-glyphs-4',
  'necrons/nihilakh',
  'necrons/novokh-dark',
  'necrons/novokh-lord-glyphs-1',
  'necrons/novokh-lord-glyphs-2',
  'necrons/novokh-lord-glyphs-3',
  'necrons/novokh-lord-glyphs-4',
  'necrons/novokh-overlord-glyphs-1',
  'necrons/novokh-overlord-glyphs-2',
  'necrons/novokh-overlord-glyphs-3',
  'necrons/novokh-overlord-glyphs-4',
  'necrons/novokh-phalanx-glyphs-1',
  'necrons/novokh-phalanx-glyphs-2',
  'necrons/novokh-phalanx-glyphs-3',
  'necrons/novokh-phalanx-glyphs-4',
  'necrons/novokh',
  'necrons/sautekh-dark',
  'necrons/sautekh-lord-glyphs-1',
  'necrons/sautekh-lord-glyphs-2',
  'necrons/sautekh-lord-glyphs-3',
  'necrons/sautekh-lord-glyphs-4',
  'necrons/sautekh-overlord-glyphs-1',
  'necrons/sautekh-overlord-glyphs-2',
  'necrons/sautekh-overlord-glyphs-3',
  'necrons/sautekh-overlord-glyphs-4',
  'necrons/sautekh',
  'necrons/szarekhan-dark',
  'necrons/szarekhan',
  'orks/bad-moons-2',
  'orks/bad-moons',
  'orks/blood-axes-copy',
  'orks/deathskulls',
  'orks/evil-sunz',
  'orks/goffs',
  'orks/gorkamorka',
  'orks/gretchin',
  'orks/orks',
  'orks/snakebites',
  'orks/snotlings',
  'orks/squigs',
  'tau/air-caste',
  'tau/au-taal',
  'tau/bork-an',
  'tau/d-yanoi',
  'tau/dalyth',
  'tau/earth-caste',
  'tau/elsy-eir',
  'tau/ethereal-caste',
  'tau/fal-shia',
  'tau/farsight-enclaves',
  'tau/fe-saan',
  'tau/fi-rios',
  'tau/fire-caste',
  'tau/ke-lshan',
  'tau/kor-tal',
  'tau/kroot',
  'tau/ksi-m-yen',
  'tau/mu-gulath',
  'tau/n-dras',
  'tau/sa-cea',
  'tau/t-au-n',
  'tau/t-au-number-0',
  'tau/t-au-number-1',
  'tau/t-au-number-2',
  'tau/t-au-number-3',
  'tau/t-au-number-4',
  'tau/t-au-number-5',
  'tau/t-au-number-6',
  'tau/t-au-number-7',
  'tau/t-au',
  'tau/t-olku',
  'tau/tash-var',
  'tau/tashvar',
  'tau/tau-num0',
  'tau/tau-num1',
  'tau/tau-num2',
  'tau/tau-num3',
  'tau/tau-num4',
  'tau/tau-num5',
  'tau/tau-num6',
  'tau/tau-num7',
  'tau/tau',
  'tau/vash-ya',
  'tau/vior-la',
  'tau/water-caste',
  'tau/yo-vai',
  'tyranid/tyranids',
  'xenos/blackstone-fortress',
  'xenos/hrud',
  'xenos/jokaero',
  'xenos/xenos',
]
